name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet:
    env:
      MY_ENV: "MY ENV TEST"
    runs-on: ubuntu-latest
    steps:
    - name: Greet the user
      run: echo "Hello World!"
    - name: Run a multi-line script
      run: |
        echo "Hello $MY_ENV"
        echo "Hello $GITHUB_ACTOR"
